---
- hosts: linux
  tasks:
   - name: create file
     file:
       path: /home/ansible/hostname.conf
       state: touch
   - name: add a line
     lineinfile:
         dest: /home/ansible/hostname.conf
         line: Hostname={{ ansible_hostname }}
         state: present   
